// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetKind } from "./AssetKind";

export type Asset = { id: string, kind: AssetKind, 
/**
 * original filename, display only — never used as a path
 */
name: string, 
/**
 * sha-256 hex of file bytes; upload key
 */
hash: string, duration: number | null, width: number | null, height: number | null, fps: number | null, hasAudio: boolean, mimeType: string, };
