// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChromaKey } from "./ChromaKey";
import type { ColorAdjustments } from "./ColorAdjustments";
import type { Crop } from "./Crop";
import type { FilterPreset } from "./FilterPreset";
import type { Keyframes } from "./Keyframes";
import type { TextStyle } from "./TextStyle";
import type { Transform } from "./Transform";
import type { Transition } from "./Transition";

export type Clip = { "type": "video", id: string, start: number, duration: number, assetId: string, sourceIn: number, 
/**
 * playback rate 0.25..4; source consumed = duration × speed
 */
speed: number, volume: number, muted: boolean, flipH: boolean, flipV: boolean, chromaKey: ChromaKey | null, backgroundBlur: boolean, crop: Crop | null, transform: Transform, keyframes: Keyframes, adjustments: ColorAdjustments, filter: FilterPreset | null, fadeIn: number, fadeOut: number, transitionOut: Transition | null, } | { "type": "image", id: string, start: number, duration: number, assetId: string, flipH: boolean, flipV: boolean, chromaKey: ChromaKey | null, backgroundBlur: boolean, crop: Crop | null, transform: Transform, keyframes: Keyframes, adjustments: ColorAdjustments, filter: FilterPreset | null, fadeIn: number, fadeOut: number, transitionOut: Transition | null, } | { "type": "audio", id: string, start: number, duration: number, assetId: string, sourceIn: number, 
/**
 * playback rate 0.25..4; source consumed = duration × speed
 */
speed: number, volume: number, fadeIn: number, fadeOut: number, } | { "type": "text", id: string, start: number, duration: number, 
/**
 * may contain explicit \n line breaks
 */
text: string, style: TextStyle, transform: Transform, keyframes: Keyframes, 
/**
 * rendered block size in canvas px, measured by the editor whenever
 * text/style change; 0 = unknown (renderer falls back to centered)
 */
measuredWidth: number, measuredHeight: number, fadeIn: number, fadeOut: number, };
