// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";

export type Keyframe = { 
/**
 * clip-local time (s from clip start)
 */
t: number, value: number, 
/**
 * easing INTO the next keyframe
 */
easing: Easing, };
