// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Encoder quality tier — a closed enum so clients can never inject
 * arbitrary encoder arguments.
 */
export type RenderQuality = "draft" | "standard" | "high";
