// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAlign } from "./TextAlign";

export type TextStyle = { 
/**
 * must be one of the bundled fonts
 */
fontFamily: string, 
/**
 * px at canvas resolution
 */
fontSize: number, 
/**
 * 400 or 700
 */
fontWeight: number, italic: boolean, 
/**
 * #rrggbb
 */
color: string, backgroundColor: string | null, outlineColor: string | null, outlineWidth: number, align: TextAlign, };
