// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Clip } from "./Clip";
import type { TrackKind } from "./TrackKind";

export type Track = { id: string, kind: TrackKind, name: string, muted: boolean, hidden: boolean, 
/**
 * non-overlapping, sorted by start
 */
clips: Array<Clip>, };
