// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Transform = { 
/**
 * center offset from canvas center, canvas px (y down)
 */
x: number, y: number, 
/**
 * 1 = "fit" inside canvas
 */
scale: number, 
/**
 * degrees, clockwise
 */
rotation: number, 
/**
 * 0..1
 */
opacity: number, };
